config/routes.rb
Rails.application.routes.draw do
  get "/up" => "rails/health#show", as: :rails_health_check

  devise_for :users

  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine, at: "/good_job"
    mount Blazer::Engine, at: "/blazer"
  end

  root to: "home#index"

  get "/leaderboard", to: "players#index"

  resources :players, only: :show, param: :name do
    collection do
      get :search
    end
  end

  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server_error"
end

app/models/a801/player.rb
module A801
  class Player < ApplicationRecord
    establish_connection(:a801) unless Rails.env.test?

    self.abstract_class = true if Rails.env.test?
    self.table_name = "player"
  end
end

app/models/player.rb
class Player < ApplicationRecord
  include PlayerExtensions::Ratio
  include PlayerExtensions::NormalScore
  include PlayerExtensions::SurvivorScore
  include PlayerExtensions::RacingScore
  include PlayerExtensions::DefilanteScore
  include PlayerExtensions::Level
  include PlayerExtensions::Leaderboard

  MAX_NAME_LENGTH = 100
  TAG_REGEX = /#\d{4}$/
  ADMIN_TAG = "0001"
  ADMIN_TITLES = %w[440 442 444 445 446 447 448 449 450 451 452 453 454 534].freeze
  MODERATOR_TAG = "0010"
  SENTINEL_TAG = "0015"
  MAP_CREW_TAG = "0020"

  has_one :category_standing, autosave: true, dependent: :destroy
  has_many :change_logs, dependent: :destroy
  has_one :change_logs_past_day, -> { past_day }, class_name: "ChangeLog"
  has_one :change_logs_past_7_days
  has_one :change_logs_past_30_days

  scope :qualified, -> { where.not(stats_reliability: 2) }
  scope :disqualified, -> { where(stats_reliability: 2) }

  validates :a801_id, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true, length: { maximum: MAX_NAME_LENGTH }

  after_validation :prepare_name
  before_save :update_scores, :log_changes # Order matters

  delegate :normal_score, :normal_rank, :previous_normal_rank,
           :survivor_score, :survivor_rank, :previous_survivor_rank,
           :racing_score, :racing_rank, :previous_racing_rank,
           :defilante_score, :defilante_rank, :previous_defilante_rank,
           to: :category_standing, allow_nil: true

  def self.normalize_name(name)
    prefix, first_alpha, remainder = name.partition(/[A-Za-z]/)
    prefix + first_alpha.upcase + remainder.downcase
  end

  def to_param
    name.downcase
  end

  def disqualified?
    stats_reliability == 2
  end

  private

  def prepare_name
    return if name.blank?

    normalized_name = self.class.normalize_name(name)
    normalized_name += "#0000" unless normalized_name.match?(TAG_REGEX)

    self.name = normalized_name
  end

  def update_scores
    standing = category_standing || build_category_standing

    standing.normal_score = calculate_normal_score
    standing.survivor_score = calculate_survivor_score
    standing.racing_score = calculate_racing_score
    standing.defilante_score = calculate_defilante_score
  end

  def log_changes
    return if new_record?

    tracked_attributes = ChangeLog.column_names.excluding(%w[id player_id created_at updated_at])
    player_changes = changes.slice(*tracked_attributes)
    category_standing_changes = category_standing&.changes&.slice(*tracked_attributes) || {}
    all_changes = player_changes.merge(category_standing_changes)

    return if all_changes.empty?

    calculated_deltas = all_changes.transform_values { |(old, new)| new - old }
    past_day_log = change_logs.past_day.first

    if past_day_log
      merged_attributes = calculated_deltas.each_with_object({}) do |(attr, delta), memo|
        current_value = past_day_log[attr] || 0
        memo[attr] = current_value + delta
      end

      past_day_log.update!(merged_attributes)
    else
      change_logs.create!(calculated_deltas)
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  SEARCH_TERM_MIN_LENGTH = 3
  SEARCH_TERM_REGEX = /\A\+?[A-Za-z0-9_#]+\z/ # Ruby-specific for server-side validation
  SEARCH_TERM_REGEX_JS = /^\+?[A-Za-z0-9_#]+$/ # JS-specific for client-side validation

  before_action :set_statistic, :set_category, :set_time_range, only: :index

  def index
    @current_page = params[:page].to_i.zero? ? 1 : params[:page].to_i

    # We know that the Player.ranked_by is always going to return more than enough records for the max amount
    # of pages, since we simply order differently based on the statistic and time range.
    @pagy, @players = pagy(:countless, Player.ranked_by(@statistic, @time_range), last: Pagy.options[:max_pages])
  end

  def show
    @player = Player.find_by!(name: Player.normalize_name(params[:name]))
    @past_day = @player.change_logs_past_day
    @past_7_days = @player.change_logs.past_7_days.to_a
    @past_30_days = @player.change_logs.past_30_days.to_a
  end

  def search
    @search_term = params[:term].to_s.strip
    return @search_valid = true if @search_term.blank?

    @search_valid = valid_search_term?
    return unless @search_valid

    exact_match = Player.find_by(name: Player.normalize_name(@search_term))
    return redirect_to player_path(name: exact_match.name) if exact_match

    @search_results = SearchService.new(@search_term).perform_search
  end

  private

  def set_statistic
    @statistic = if params[:statistic].present? &&
                    Player::LEADERBOARD_STATISTICS.values.flatten.include?(params[:statistic].to_sym)
                   params[:statistic].to_sym
    else
                   Player::LEADERBOARD_DEFAULT
    end
  end

  def set_category
    @category = Player::LEADERBOARD_STATISTICS.key(
      Player::LEADERBOARD_STATISTICS.values.find { |types| types.include?(@statistic) }
    )
  end

  def set_time_range
    @time_range = if params[:time_range].present? && Player::TIME_RANGES.include?(params[:time_range].to_sym)
                    params[:time_range].to_sym
    else
                    Player::TIME_RANGE_DEFAULT
    end
  end

  def valid_search_term?
    @search_term.length >= SEARCH_TERM_MIN_LENGTH && @search_term.match?(SEARCH_TERM_REGEX)
  end
end

app/helpers/player_helper.rb
module PlayerHelper
  def name_color(name)
    tag = name.split("#").last

    case tag
    when Player::ADMIN_TAG
      "text-admin"
    when Player::MODERATOR_TAG
      "text-moderator"
    when Player::SENTINEL_TAG
      "text-sentinel"
    when Player::MAP_CREW_TAG
      "text-map-crew"
    else
      "text-primary"
    end
  end

  def display_ratio(ratio)
    return unless ratio.present? && ratio.positive?

    "(#{decimal_to_percentage(ratio)})"
  end

  def decimal_to_percentage(decimal)
    number_to_percentage(decimal * 100, precision: 2)
  end

  def humanized_title(title)
    translated_title = I18n.t(title, scope: "players.titles", default: title)

    formatted_title = if Player::ADMIN_TITLES.include?(title)
      "<span class='text-admin-title fw-bold'>#{translated_title}</span>"
    else
      translated_title
    end

    "«#{formatted_title}»"
  end
end

app/views/players/_player.html.erb
<div class="card player-card">
  <div class="card-body">
    <div class="d-flex align-items-center gap-3">
      <h4 class="mb-0"><%= player.name %></h4>
      <div class="vr"></div>
      <span><%= t('.score', score: number_with_delimiter(player.normal_score)) %></span>
      <span class="ms-auto"><%= "##{player.normal_rank}" %></span>
    </div>

    <div class="card-separator"></div>

    <div class="row">
      <div class="col-6 col-md-3">
        <span class="d-block fw-bold"><%= Player.human_attribute_name(:rounds_played) %></span>
        <%= number_with_delimiter(player.rounds_played) %>
      </div>
      <div class="col-6 col-md-3">
        <span class="d-block fw-bold"><%= Player.human_attribute_name(:saved_mice) %></span>
        <%= number_with_delimiter(player.saved_mice) %>
      </div>
      <div class="col-6 col-md-3">
        <span class="d-block fw-bold"><%= Player.human_attribute_name(:firsts) %></span>
        <%= number_with_delimiter(player.firsts) %>
      </div>
      <div class="col-6 col-md-3">
        <span class="d-block fw-bold"><%= Player.human_attribute_name(:cheese_gathered) %></span>
        <%= number_with_delimiter(player.cheese_gathered) %>
      </div>
    </div>
  </div>
</div>

app/views/players/index.html.erb
<% set_meta_tags(canonical: leaderboard_url) %>

<h1 class="text-primary mb-2"><%= title(t("players.index.title")) %></h1>

<div class="d-flex gap-3 mb-4 mb-md-5">
  <span><%= t(@category, scope: "players.show.categories") %></span>

  <div class="vr mx-2"></div>

  <span><%= t(@statistic, scope: "activerecord.attributes.player") %></span>

  <div class="vr mx-2"></div>

  <span><%= t(@time_range, scope: "players.index.time_ranges") %></span>
</div>

<div class="d-flex">
  <%= render "players/index/leaderboard_selection" %>
</div>

<% if @players.empty? && @time_range == :past_day %>
  <div class="d-flex flex-column align-items-center justify-content-center h-100 gap-5 py-4">
    <%= image_tag "not_found.webp", alt: t("errors.not_found.image_alt"), class: "hero-image" %>

    <div class="d-flex flex-column align-items-center">
      <h1 class="text-center text-primary"><%= t("players.index.no_data.title") %></h1>
      <span class="text-center"><%= t("players.index.no_data.message") %></span>
    </div>
  </div>
<% else %>
  <div class="my-3 my-md-4">
    <%== @pagy.input_nav_js(:bootstrap) %>
  </div>

  <%= render PlayerLeaderboard.new(players: @players, category: @category, statistic: @statistic,
                                   time_range: @time_range, current_page: @current_page) %>

  <div class="mt-3 mt-md-4">
    <%== @pagy.input_nav_js(:bootstrap) %>
  </div>
<% end %>

app/views/players/search.html.erb
<% set_meta_tags(canonical: search_players_url) %>

<div class="d-flex flex-column flex-grow-1 justify-content-center">
  <div class="text-center mb-4 mb-md-5">
    <h1 class="text-primary mb-2"><%= title(t("players.search.title")) %></h1>
    <span><%= t("players.search.subtitle") %></span>
  </div>

  <div class="search-container">
    <%= form_tag search_players_path,
                 method: :get,
                 novalidate: true,
                 data: {
                   controller: "search-validation",
                   action: "submit->search-validation#validate",
                   search_validation_message_value: t("players.search.requirements_html")
                 } do %>
      <div class="search-bar" data-search-validation-target="searchBar">
        <%= text_field_tag :term, nil,
                           required: true,
                           autocomplete: :off,
                           value: @search_term,
                           class: "search-input",
                           placeholder: t("players.search.placeholder"),
                           pattern: PlayersController::SEARCH_TERM_REGEX_JS,
                           minlength: PlayersController::SEARCH_TERM_MIN_LENGTH,
                           maxlength: Player::MAX_NAME_LENGTH,
                           data: { search_validation_target: "input" } %>

        <%= button_tag id: "reset_search", type: :reset, class: "btn btn-search" do %>
          <i class="bi bi-x-lg"></i>
        <% end %>

        <%= button_tag id: "submit_search",
                       type: :submit,
                       class: "btn btn-search",
                       name: nil do %>
          <i class="bi bi-search"></i>
        <% end %>
      </div>
    <% end %>

    <% if @search_term.present? && @search_valid %>
      <% if @search_results.any? %>
        <div class="card">
          <div class="card-body">
            <h4 class="text-center mb-0"><%= t("players.search.results_title") %></h4>

            <div class="card-separator"></div>

            <div class="search-results">
              <% @search_results.each do |result| %>
                <div class="search-result">
                  <%= link_to player_path(result), class: "underlined-link" do %>
                    <%= result.name %>
                  <% end %>
                </div>

                <div class="hr-thin"></div>
              <% end %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="d-flex flex-column align-items-center gap-5">
          <span class="text-center"><%= t("players.search.no_results") %></span>
          <%= image_tag "not_found.webp", alt: t("errors.not_found.image_alt"), class: "hero-image" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/players/show.html.erb
<div class="title-container">
  <h1 class="<%= name_color(@player.name) %> mb-0"><%= title(@player.name) %></h1>

  <% if @player.disqualified? %>
    <div class="disqualified-badge">
      <span class="text-danger fw-bold"><%= t("players.show.disqualified") %></span>
    </div>
  <% end %>
</div>

<div class="d-flex gap-3 mb-4 mb-md-5">
  <span><%= l(@player.registration_date, format: :short) %></span>

  <div class="vr mx-2"></div>

  <span><%= sanitize(humanized_title(@player.title)) %></span>
</div>

<div class="d-flex mb-3 mb-md-4">
  <div class="d-flex bg-secondary rounded-4 px-4">
    <ul id="profileTabs" class="nav nav-underline gap-4">
      <li class="nav-item">
        <button id="statistics" class="nav-link py-3 active" type="button" data-bs-toggle="tab"
                data-bs-target="#statisticsTabPane">
          <%= t("players.show.statistics") %>
        </button>
      </li>
      <li class="nav-item">
        <button id="performance" class="nav-link py-3" type="button" data-bs-toggle="tab"
                data-bs-target="#performanceTabPane">
          <%= t("players.show.performance") %>
        </button>
      </li>
    </ul>
  </div>
</div>

<div id="profileTabTypes" class="tab-content">
  <div id="statisticsTabPane" class="tab-pane fade show active" role="tabpanel">
    <div class="statistics-grid">
      <div class="normal-stats">
        <%= render "players/show/normal_stats", player: @player, past_day: @past_day %>
      </div>
      <div class="racing-stats">
        <%= render "players/show/racing_stats", player: @player, past_day: @past_day %>
      </div>
      <div class="survivor-stats">
        <%= render "players/show/survivor_stats", player: @player, past_day: @past_day %>
      </div>
      <div class="defilante-stats">
        <%= render "players/show/defilante_stats", player: @player, past_day: @past_day %>
      </div>
    </div>
  </div>

  <div id="performanceTabPane" class="tab-pane fade" role="tabpanel">
    <div class="row g-3">
      <div class="col-12">
        <%= render "players/show/change_logs", player: @player,
                                               past_7_days: @past_7_days,
                                               past_30_days: @past_30_days %>
      </div>
    </div>
  </div>
</div>