config/routes.rb
Rails.application.routes.draw do
  get "/up" => "rails/health#show", as: :rails_health_check

  devise_for :users

  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine, at: "/good_job"
    mount Blazer::Engine, at: "/blazer"
  end

  root to: "home#index"

  get "/leaderboard", to: "players#index"

  resources :players, only: :show, param: :name do
    collection do
      get :search
    end
  end

  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server_error"
end

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
<link rel="manifest" href="/favicons/site.webmanifest">
<link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/favicons/favicon.ico">

<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/favicons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <%= render FlashMessage.new(type, message) %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-md bg-secondary">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand d-flex align-items-center gap-2" do %>
      <%= image_tag "logo.webp", alt: t("navbar.brand_alt") %>
      <span class="d-md-none text-primary soopafresh"><%= t("navbar.brand_short") %></span>
      <span class="d-none d-md-inline-block text-primary soopafresh"><%= t("navbar.brand") %></span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
      <i class="bi bi-list"></i>
    </button>

    <div id="navbarContent" class="collapse navbar-collapse">
      <ul class="navbar-nav ms-auto mt-2 mt-md-0">
        <li class="nav-item">
          <%= link_to leaderboard_path, class: "nav-link d-flex align-items-center gap-2" do %>
            <i class="bi bi-trophy-fill"></i>
            <span><%= t("navbar.leaderboard") %></span>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to search_players_path, class: "nav-link d-flex align-items-center gap-2" do %>
            <i class="bi bi-search"></i>
            <span><%= t("navbar.search") %></span>
          <% end %>
        </li>

        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to good_job_path, target: "_blank", class: "nav-link d-flex align-items-center gap-2" do %>
                <i class="bi bi-database-fill-gear"></i>
                <span><%= t("navbar.jobs") %></span>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to blazer_path, target: "_blank", class: "nav-link d-flex align-items-center gap-2" do %>
                <i class="bi bi-pie-chart-fill"></i>
                <span><%= t("navbar.blazer") %></span>
              <% end %>
            </li>
          <% end %>

          <li class="nav-item">
            <%= button_to destroy_user_session_path, method: :delete,
                                                     class: "nav-link d-flex align-items-center gap-2" do %>
              <i class="bi bi-box-arrow-right"></i>
              <span><%= t("navbar.logout") %></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100" lang="en" data-bs-theme="dark">
  <head>
    <%= display_meta_tags(site: t("meta.title")) %>
    <meta charset="utf-8">
    <meta name="description" content="<%= t("meta.description") %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%# Turbo 8 %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
    <meta name="view-transition" content="same-origin">

    <%= render "layouts/favicon" %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <% if defined? Sentry %>
      <%= Sentry.get_trace_propagation_meta.html_safe %>
    <% end %>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render "layouts/navbar" %>

    <div class="flex-grow-1 position-relative">
      <div class="container d-flex flex-column py-4 py-md-5 h-100">
        <%= yield %>
      </div>
      <div class="flash-messages-container">
        <%= render partial: "layouts/flash_messages", flash: flash %>
      </div>
    </div>
  </body>
</html>